name: Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Run build
      run: go build .

    - name: Run vet & lint
      run: |
        go get -u golang.org/x/lint/golint
        go vet .
        golint .
